### ISSUE TITLE
Segmentation fault with multi-volume SPEC equilibria

### ISSUE THREAD

**Issue by abaillod** [hiddenSymmetries/simsopt#135]
Hello!

I am trying to run simsopt to optimize some SPEC equilibria and I am running into some bugs I don't know how to solve. Note that I am new to python so it is very likely that some of these "bugs" are introduced by myself... Nevertheless, I would appreciate if someone could help me understand what is going on.

So, let me first say that I installed simsopt and SPEC py_wrappers, and it seems to work fine - I was able to run the example `simsopt/examples/2_Intermediate/eliminate_magnetic_islands.py`.

Now, I want to do the same kind of optimization but with a multi-volume, finite beta SPEC equilibrium (input file: 
[Input_000.txt](https://github.com/hiddenSymmetries/simsopt/files/7037554/Input_000.txt)). I tried to generate a `Spec` object and to run SPEC with the following script: 

```
import logging
from simsopt.mhd.spec import Spec

logging.basicConfig(filename='loggerOutput.log', level=logging.DEBUG)

s = Spec('Input_000.sp')

s.run()
```

This doesn't seem to work - I get a segmentation fault. Terminal output:
```
(simsopt) abaillod@spcpc602:~/Physics/Optimization/RotatingEllipse/FixedBoundary/BoundaryOptimization/test> python test.py
No module named 'vmec'
readin :            : 
readin : ********** : Igeometry=  3 ; Istellsym=  1 ; Lreflect=  0 ;
readin :            : Lfreebound=  0 ; phiedge=  1.000000000000000E+00 ; curtor=  0.000000000000000E+00 ; curpol=  0.000000000000000E+00 ;
readin :            : gamma=  0.000000000000000E+00 ;
readin :            : Nfp=  5 ; Nvol=  8 ; Mvol=  8 ; Mpol=  6 ; Ntor=  4 ;
readin :            : pscale=  1.00000E+00 ; Ladiabatic= 0 ; Lconstraint=  3 ; mupf: tol,its=  1.00E-12 , 128 ;
readin :            : Lrad = 12, 6, 6, 6, 6, 6, 6, 6,
readin :            : 
readin : ********** : Linitialize=  0 ;LautoinitBn=  1 ; Lzerovac= 0 ; Ndiscrete= 2 ;
readin :            : Nquad=  -1 ; iMpol=  -4 ; iNtor=  -4 ;
readin :            : Lsparse= 0 ; Lsvdiota= 0 ; imethod= 3 ; iorder= 2 ; iprecon= 1 ; iotatol= -1.00000E+00 ;
readin :            : Lextrap= 0 ; Mregular= -1 ; Lrzaxis= 2 ; Ntoraxis= 3 ;
readin :            : 
readin : ********** : LBeltrami= 4 ; Linitgues= 1 ; Lmatsolver= 3 ; LGMRESprec= 1 ; NiterGMRES= 200 ; epsGMRES=  1.00000E-14 ; epsILU=  1.00000E-12 ;
readin :            : 
readin : ********** : Lfindzero= 2 ;
readin :            : escale=  0.00000E+00 ; opsilon=  1.00000E+00 ; pcondense=  4.000 ; epsilon=  1.00000E+00 ; wpoloidal= 1.0000 ; upsilon=  1.00000E+00 ;
readin :            : forcetol=  1.00000E-12 ; c05xmax=  1.00000E-06 ; c05xtol=  1.00000E-12 ; c05factor=  1.00000E-04 ; LreadGF= T ; 
readin :            : mfreeits=   0 ; gBntol=  1.00000E-06 ; gBnbld=  6.66000E-01 ;
readin :            : vcasingeps=  1.00000E-12 ; vcasingtol=  1.00000E-08 ; vcasingits=     8 ; vcasingper=     1 ;
readin :            : 
readin : ********** : odetol=  1.00E-07 ; nPpts=     0 ;
readin :            : LHevalues= F ; LHevectors= F ; LHmatrix= F ; Lperturbed= 0 ; dpp= -1 ; dqq= -1 ; dRZ=  1.00000000E-05 ; Lcheck=  0 ; Ltiming= F ;
readin :            : 
readin :            : myid=  0 ; Rscale= 1.000000000000000E+01 ;
preset :            : myid=  0 ; Mrad= 12 : Lrad= 12,  6,  6,  6,  6,  6,  6,  6,
preset : ********** : LBsequad= F , LBnewton= F , LBlinear= T ;
preset :            : 
preset : ********** : Nquad=  -1 ; mn=   59 ; NGdof=   819 ; NAdof=   705,   768,   768,   768,   768,   768,   768,   768,
preset :            : 
preset : ********** : Nt=    48 ; Nz=    32 ; Ntz=     1536 ;
In __init__, si.istellsym= 1  stellsym= True
In run, si.istellsym= 1  stellsym= True
readin :            : 
readin : ********** : Igeometry=  3 ; Istellsym=  1 ; Lreflect=  0 ;
readin :            : Lfreebound=  0 ; phiedge=  1.000000000000000E+00 ; curtor=  0.000000000000000E+00 ; curpol=  0.000000000000000E+00 ;
readin :            : gamma=  0.000000000000000E+00 ;
readin :            : Nfp=  5 ; Nvol=  8 ; Mvol=  8 ; Mpol=  6 ; Ntor=  4 ;
readin :            : pscale=  1.00000E+00 ; Ladiabatic= 0 ; Lconstraint=  3 ; mupf: tol,its=  1.00E-12 , 128 ;
readin :            : Lrad = 12, 6, 6, 6, 6, 6, 6, 6,
readin :            : 
readin : ********** : Linitialize=  0 ;LautoinitBn=  1 ; Lzerovac= 0 ; Ndiscrete= 2 ;
readin :            : Nquad=  -1 ; iMpol=  -4 ; iNtor=  -4 ;
readin :            : Lsparse= 0 ; Lsvdiota= 0 ; imethod= 3 ; iorder= 2 ; iprecon= 1 ; iotatol= -1.00000E+00 ;
readin :            : Lextrap= 0 ; Mregular= -1 ; Lrzaxis= 2 ; Ntoraxis= 3 ;
readin :            : 
readin : ********** : LBeltrami= 4 ; Linitgues= 1 ; Lmatsolver= 3 ; LGMRESprec= 1 ; NiterGMRES= 200 ; epsGMRES=  1.00000E-14 ; epsILU=  1.00000E-12 ;
readin :            : 
readin : ********** : Lfindzero= 2 ;
readin :            : escale=  0.00000E+00 ; opsilon=  1.00000E+00 ; pcondense=  4.000 ; epsilon=  1.00000E+00 ; wpoloidal= 1.0000 ; upsilon=  1.00000E+00 ;
readin :            : forcetol=  1.00000E-12 ; c05xmax=  1.00000E-06 ; c05xtol=  1.00000E-12 ; c05factor=  1.00000E-04 ; LreadGF= T ; 
readin :            : mfreeits=   0 ; gBntol=  1.00000E-06 ; gBnbld=  6.66000E-01 ;
readin :            : vcasingeps=  1.00000E-12 ; vcasingtol=  1.00000E-08 ; vcasingits=     8 ; vcasingper=     1 ;
readin :            : 
readin : ********** : odetol=  1.00E-07 ; nPpts=     0 ;
readin :            : LHevalues= F ; LHevectors= F ; LHmatrix= F ; Lperturbed= 0 ; dpp= -1 ; dqq= -1 ; dRZ=  1.00000000E-05 ; Lcheck=  0 ; Ltiming= F ;
readin :            : 
Segmentation fault (core dumped)
```

And the file loggerOutput.log:
```
INFO:simsopt.mhd.spec:Initializing a SPEC object from file: Input_000.sp
DEBUG:simsopt.mhd.spec:Entering init
DEBUG:simsopt.mhd.spec:Done with initialize_inputs
DEBUG:simsopt.mhd.spec:Done with read_inputlists_from_file
DEBUG:simsopt.mhd.spec:About to call broadcast_inputs
DEBUG:simsopt.mhd.spec:About to call preset
DEBUG:simsopt.mhd.spec:Done with init
INFO:simsopt.mhd.spec:Preparing to run SPEC.
INFO:simsopt.mhd.spec:Running SPEC using filename Input_000_000_000000
DEBUG:simsopt.mhd.spec:About to call check_inputs
DEBUG:simsopt.mhd.spec:About to call broadcast_inputs
DEBUG:simsopt.mhd.spec:About to call preset
```

I am not sure if this problem is related to SIMSOPT or to SPEC python wrappers though. Any help would be appreciated! 

Thank you!

**Comment by landreman** [comment]
Hi @abaillod, for that input file, the seg fault occurs on my machine too. The seg fault appears to be happening on line 327 of preset.f90: `mm = mmRZRZ(idx_mode)` because `mmRZRZ` is not allocated on the 2nd call of `preset()`. The `mmRZRZ` array is allocated once, during initialization, [in read_inputlists_from_file()](https://github.com/PrincetonUniversity/SPEC/blob/master/global.f90#L996). In standalone SPEC, I believe preset() is called just once. For a simsopt Spec object, `preset()` is [called once when the object is created](https://github.com/hiddenSymmetries/simsopt/blob/master/src/simsopt/mhd/spec.py#L207) and then again [every time Spec.run() is called](https://github.com/hiddenSymmetries/simsopt/blob/master/src/simsopt/mhd/spec.py#L272) since parameters may have changed. But `mmRZRZ` is deallocated during every call to preset() [on line 357](https://github.com/PrincetonUniversity/SPEC/blob/master/preset.f90#L357). Hence, `mmRZRZ` is not allocated on the 2nd call to preset(). I believe this issue did not occur previously because the previous SPEC input files I've used with simsopt did not have the interface data specified at the end, so `num_modes=0`, so lines 326-354 of preset.f90 did not run (it was a loop with 0 iterations so `mmRZRZ` was not accessed).

Is there any reason not to delete line 357 of preset.f90, where mmRZRZ is deallocated? It's not clear to me that deallocating these arrays there is necessary. When I comment out that line, your input file now runs fine with simsopt+spec. Right before the arrays are allocated in global.f90 line 996, it might be necessary to re-insert that line `if(allocated(mmRZRZ)) deallocate(mmRZRZ, nnRZRZ, allRZRZ)` so multiple spec input files can be read, e.g. for the simsopt unit tests since they involve different spec files.

**Comment by abaillod** [comment]
I didn't understand that `preset()` could be called multiple times by the `Spec` object - thanks for clarifying. I had a quick look and it seems that these variables are the only problematic ones - I will propose a fix on the SPEC master branch.

Thank you for your help!
