### ISSUE TITLE
Wrong Volume Computation for SurfaceXYZTensorFourier

### ISSUE THREAD

**Issue by jlob-pf** [hiddenSymmetries/simsopt#345]
The Volume computation of the SurfaceXYZTensorFourier representation yields wrong the results which results in a false computation of the boozer surface. The residual actually decreases to values of e-2, but the two surface absolutely do not coincide. I prepared two packages, one which just shows how the three surfaces computed by boozer.py have the same volume but completely different shapes (two of them should have volume close to zero) and the other packages which contains my slightly changed boozer.py version. The Plasma boundary and coils are taken from Rogerio's Jorge Single Optimization Paper. It is a QA configuration.
[Boozer.py_test.zip](https://github.com/hiddenSymmetries/simsopt/files/12294480/Boozer.py_test.zip)
[Test_SurfaceXYZTensorFourier.zip](https://github.com/hiddenSymmetries/simsopt/files/12294481/Test_SurfaceXYZTensorFourier.zip)

**Comment by landreman** [comment]
It's not clear to me that the volume calculation is the location of the problem. The surface after LBFGS is crazy and self-intersecting so I wouldn't trust the volume calculation, and my instinct is that the problem is elsewhere. If you haven't already, I'd suggest making a poincare plot via simsopt after line 85 of `boozer.py` to make sure the magnetic field is what it is supposed to be, and there is a flux surface close to the loaded surface `s`. In other words, eliminate the possibility that there is an issue with loading in the coils and scaling the currents in lines 65-73. If that checks out, maybe the sign of G0 and/or iota could be off (sign conventions are always a pain), or the LBFGS optimizer is taking too big a step which takes it into crazy-land. @andrewgiuliani is the expert on `BoozerSurface` - any suggestions?

**Comment by andrewgiuliani** [comment]
Hi Jim, just to follow up after our zoom call. The volume calculation uses quadrature and if the surface is crazy looking, you likely are not obtaining a good approximation of the volume enclosed by the surface.  Also the surfaces shouldn't self-intersect.  @landreman made some nice suggestions and are a good first debugging step.

**Comment by andrewgiuliani** [comment]
You should also take a look at the unit tests for the BoozerSurface calculations, where surfaces for the HSX, NCSX, and other configurations are calculated.

https://github.com/hiddenSymmetries/simsopt/blob/c859dfb33e9a193a064e7221b4100b83a8950575/tests/geo/test_boozersurface.py#L219
