### ISSUE TITLE
Possible bug in test_mpi.py

### ISSUE THREAD

**Issue by mbkumar** [hiddenSymmetries/simsopt#59]
Hello Matt,

I am wondering if there is a bug in https://github.com/hiddenSymmetries/simsopt/blob/master/tests/solve/test_mpi.py#L132

**Comment by landreman** [comment]
There is the issue we discussed before that lines 120-133 should be indented. But you think there is another problem with line 132? It looks reasonable to me, asserting agreement of two methods for testing whether the processor has rank 0.

**Comment by mbkumar** [comment]
I am talking about that one line of code. 
I have one doubut about the statement `assertEqual(m.proc0_world, rank_world == 0)`.
`rank_world==0` could be True or False. If it evaluates to True, rank_world is 0, but now you are comparing m.proc0_world with binary True (or numerically 1). Am I missing something?

**Comment by landreman** [comment]
Consider these 4 cases. 

Case 1: The code works properly and the process has rank 0. Then `m.proc0_world` is True and `rank_world==0` is True. Since `True==True` evaluates to True, the assertion passes, as it should.

Case 2: The code works properly and the process has rank >0. Then `m.proc0_world` is False and `rank_world==0` is False. Since `False==False` evaluates to True, the assertion passes, as it should.

Case 3: Something has gone wrong, so `m.proc0_world` is True but `rank_world==0` is False. Since `True==False` evaluates to False, the assertion fails, as it should.

Case 4: Something has gone wrong, so `m.proc0_world` is False but `rank_world==0` is True. Since `False==True` evaluates to False, the assertion fails, as it should.

**Comment by mbkumar** [comment]
Thanks.   I was thinking m.proc0_world as an integer. My bad. Closing the
issue.

Bharat
