### ISSUE TITLE
Modify caching implementation for Optimizable object

### ISSUE THREAD

**Issue by mbkumar** [hiddenSymmetries/simsopt#63]
At present, Optimizable class implements caching by using a boolean variable to denote a new input is present. With this approach, all the objective functions in an Optimizable class are evaluated whenever a new input is supplied. And the results are stored in the cache. If one of the objective functions is called again, the cached value is used. This has the drawback of possibly requiring expensive evaluations of all objective functions even if most of them are not needed for a given problem. 

Alternative implementations:
1) Use a separate boolean variable to denote new input for all objective functions. A new input sets all the variables for the objective functions. Whenever one of the objective functions is called, the called function refers to its own variable to either return the cache or do a calculation and update the cache. To minimize the workload on the developers, develop a method decorator that can handle this automatically, so that developers of objective functions don't have to deal with caching at all.
Drawback: In addition to the cache, another set of variables have to be used. 
Pros: No need to deal with cache for new inputs, which could be costly.
2) Alternatively, don't use boolean variables to denote new_x. Instead, invalidate cache, whenever a new input is given. When an objective function is called, cache is checked and if not in a valid state, the function is computed and cache is updated.
Drawback: Invalidating (deleting) and rebuilding cache could be costly in terms of memory operations..
Pros: No need to store any additional variables.

**Comment by mbkumar** [comment]
@florianwechsung, @landreman , 

Which of the alternative implementations do you prefer?

**Comment by florianwechsung** [comment]
I prefer 2. Here is how we implemented that approach in the C++ geo classes:

We have a `CachedArray` class, that consists of an Array and a Boolean. The boolean just says whether that array is up-to-date.

```
template<class Array>
struct CachedArray {
    Array data;
    bool status;
    CachedArray(Array _data) : data(_data), status(false) {}
};
```

Each Geometric object, then has a cache, which is just a dict mapping a `string` to a `CachedArray`:
```
        map<string, CachedArray<Array>> cache;
```
and has a function `check_the_cache` that checks the cache. If the key doesn't exist, the array is created and then filled by calling `impl`. If the key exists but has status `false`, we also call `impl`, if the key exists and the status is true, we just return the Array.

```
        Array& check_the_cache(string key, vector<int> dims, std::function<void(Array&)> impl){
            auto loc = cache.find(key);
            if(loc == cache.end()){ // Key not found --> allocate array
                loc = cache.insert(std::make_pair(key, CachedArray<Array>(xt::zeros<double>(dims)))).first; 
            }
            if(!((loc->second).status)){ // needs recomputing
                impl((loc->second).data);
                (loc->second).status = true;
            }
            return (loc->second).data;
        }
```

This is used as follows:

```
        Array& gamma() {
            return check_the_cache("gamma", {numquadpoints, 3}, [this](Array& A) { return gamma_impl(A, this->quadpoints);});
        }
```

The `invalidate_cache` function is then pretty lightweight, as it just iterates over the dict and sets a bunch of bools to false:

```
        void invalidate_cache() {
            for (auto it = cache.begin(); it != cache.end(); ++it) {
                (it->second).status = false;
            }
        }
```

For the magnetic field, we have something slightly more involved, as the shape of the arrays might change if the user wants to evaluate the B field at more or less points. In that case we also check whether the array that already exists in the cache has the right shape.

**Comment by landreman** [comment]
We should be sure to cover one common situation, which arises for Vmec, Spec, Booz_xform, and probably any other significant physics code we add in the future. In these cases, there is one expensive computation - running the external code - and that computation produces many outputs (In the case of VMEC there are many outputs like iota_edge, iota_axis, aspect, the rmnc/zmns arrays, ...). In this case it's not really needed to have separate cached values for each separate code output, and in fact it could be kind of a pain to do that for each of the >100 data fields in a VMEC output file. It's sufficient to have a single bool that says whether the one expensive calculation needs to be redone. So presently Vmec, Spec, and Boozer have caching implemented via a `need_to_run_code` attribute that is initially True, set to False whenever the code is run, and set to True when set_dofs is called. I'm sure this scenario can be covered also by the more sophisticated systems you are discussing, but for these classes the simple system in place now works just fine.

**Comment by mbkumar** [comment]
@florianwechsung,

Thanks for the detailed explanation of your implementation of cached data. From what I understand, your implementation of CachedArray is somewhat closer to alternative 1. What I was thinking of cached data in alternative 2 was more in terms of deleting and creating new arrays in memory. In alternative 1, the boolean flag is associated with function, whereas for the CachedArray approach, the boolean flag is tied to data. As Matt pointed out, implementing caching for data from external MHD codes that return a lot of data is going to be a pain.

@florianwechsung, @landreman,
Based on the points you both mentioned, this is a new approach I can think of that will work for most of the cases.

I am going to use alternative 1, but with some changes that will accommodate alternative 2 as well.
1. Instead of just registering functions to cache the data, I'll use an identifier to group the functions. So for a group of functions, a call to any function will populate the cache such that other functions in the same group will have cached data available. The current approach can be thought of as all methods belonging to a single group. For cases like VMEC, we could use a single group approach, but for other codes which do multiple things, we could split the methods into different groups.
2. 
   a. Geometry classes can continue using cached data. All the methods in a geo class will be grouped into one group. Then there will be a single boolean variable to signify new input. A hook will be implemented so that whenever the boolean flag tied to new input is changed, the hook will be used to call the existing cache invalidating function. 
   b. This could be implemented in another way as well. Again geometry classes continue using cached data. The setter for `x` will be modified so instead of working with implementation 1, they will use implementation 2 by calling `invalidate_cache` function. The new setter will be implemented in a subclass of Optimizable probably with a name GeoOptimizable. And all geo classes will use GeoOptimizable as their superclass.  I prefer this approach.
  
Does this make sense?

**Comment by florianwechsung** [comment]
It's actually even a bit more complicated for some cases than what Matt outlined.
Let's say we have some `Objective` with output `J1`, `J2` and `J3`. Sometimes these have dependencies, so that if `J2` is computed, that also gives you `J1` for free, and if `J3` is computed, that also gives you `J1` and `J2` for free. This is the case for magnetic fields for example, where we can compute `B`, `grad B` and `hess B`. We don't just want to group things, since if you only want `B`, then that's much faster than also computing `grad B` and `hess B`. But if you want `grad B`, you get `B` for free essentially.

Thinking about this, I actually liked the way this was done previously, namely that each `Optimizable` was responsible for caching and would do it in the most appropriate way. The only common thing was the `set_dofs` method, and the `Optimizable` would use that `set_dofs` to do whatever needs to be done to realise that things have changed. In some cases that may involve just setting a boolean to true, in other case that may be iterating over a dict or so.

So maybe keeping something close to that would be a good solution and also very little effort? I.e. have a function `Optimizable.update()/Optimizable.clear()/Optimizable.recompute()` which is called whenever a dependency is updated or when the dofs are changed. Each `Optimizable` can then overload that class and do whatever it currently does whenever `set_dofs` is called.

**Comment by mbkumar** [comment]
Yes. We can't cover all the cases. But we could implement some basic
caching mechanism to address most of the needs. if a particular class
behavior calls for a different approach, overloading is the way to go.

Bharat Medasani

Engineer
Princeton Plasma Physics Lab (PPPL)

**Comment by florianwechsung** [comment]
Is having multiple groups a common case? It seems to me the common cases are:

1) all outputs computed together (e.g. vmec and spec)
2) outputs depend on each other in a non-trivial way, dependencies are required when needed (this is essentially the case for all geometric objects)
3) objects with independent output

1) can be dealt with by setting `needs_to_run` to true when calling the x setter, and then having a general way of checking that variable to see if vmec/spec needs to be rerun
2) can be dealt with by calling `invalidate_cache` when calling the x setter, and then having the object deal with dependencies
3) don't have strong feeling about how to do this one, since I don't know of any objectives that are of this type and that are expensive to evaluate or require a lot of memory. so maybe we just have a dict which we clear whenever the x setter is called

**Comment by mbkumar** [comment]
If we don't have multiple groups as common cases, we can keep the current
mechanism in x setter, and for geometry objects we can use the
invalidate_cache in the x setter.

@Matt Landreman ***@***.***>, are you OK with that?

Bharat Medasani

Engineer
Princeton Plasma Physics Lab (PPPL)
