### ISSUE TITLE
Stochastic stage-2 coil optimization

### ISSUE THREAD

**Issue by landreman** [hiddenSymmetries/simsopt#94]
It would be great to have the capability fully within simsopt to do the stage-2 problem (vary coil shapes to minimize \int (B dot n)^2 dS + regularization terms for a fixed target plasma boundary) with derivative-based stochastic optimization. No code can do this now, and this would basically combine the best features of FOCUS, DONSET, and pyPlasmaOpt. We basically have all the pieces for this, though some are now in pyPlasmaOpt. In practice, stellarator facility design activities these days use the 2-stage approach. So if we can demonstrate stochastic derivative-based stage-2 optimization, this would be a very useful tool for practical design.

**Comment by zhucaoxiang** [comment]
@landreman It looks like Bindel's group has done this, stochastic optimization with gradients (https://drive.google.com/file/d/1PmGcIOF_ynTR7_KgbzzmbyGazdTbpCN7/view). But probably there are different approaches.

**Comment by florianwechsung** [comment]
If I understand those slides directly, the bindel group uses the same approach as Jim Felix, that is they incorporate uncertainty in the design variables. This is nice because it's black box, but it doesn't allow for coil errors that break rotational and stellarator symmetry. It may be possible to extend their approach, I'm not sure.

For the case of perturbations that are modeled independently from the coil, we now have a first version in `driver_stochastic.py` of https://github.com/florianwechsung/SIMSOPT-Flux-Minimization 
Requires the `fw/vjp` branch of SIMSOPT.

**Comment by landreman** [comment]
Now implemented in #160
